name: suprashare
channels: 
  - conda-forge
dependencies:
  - python==3.6.5
  - rdkit==2018.03.1.0
  - scikit-learn==0.19.1
  - gunicorn==19.7.1
  - scipy==1.3.1
  - pytest==6.2.5
  - xarray==0.11.3
  - dash-bootstrap-components==1.1.0
  # - dash-bio
